/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;


import Datos.manoJugador;
import Datos.nodoPosicion;
import Datos.palabraDiccionario;
import XML.baseNodoXML;
import colas.colaPosicion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Valdez
 */
public class Tablero extends javax.swing.JFrame {

    AgregarJugador jugador = new AgregarJugador();
                      colaPosicion cP = new colaPosicion();
    baseNodoXML cola = new baseNodoXML();
    int contadorCola = 1;
    int contadorMano = 1;
    int contadorLISTA = 1;
    int contadorMatriz = 1;
    int auxCon = 0;
    int x,y = 0;
    int contadoX, contadoMX, contadoY, contadoMY = 1;
    int contadorM = 1;
    int punteo = 0;
    String valorAuxiliar;
    String Palabra= "";
    
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        jLabel1.setText(jugador.getListaJugadores().getUltimoJugador().getJugador()); 
        for (int i = 0; i <cola.getDimensionTablero(); i++) {
            for (int j = 0; j < cola.getDimensionTablero(); j++) {
              JButton jB = new JButton(""+cola.getMatriz().busquedaValor(i, j));
              jB.setBounds(i*(400/cola.getDimensionTablero()),j*(400/cola.getDimensionTablero()),(400/cola.getDimensionTablero()),(400/cola.getDimensionTablero()));  
              add(jB);
              jB.addActionListener (new ActionListener(){public void actionPerformed(ActionEvent e){
                  jB.setText(valorAuxiliar);
                  cola.getMatriz().insertar(jB.getX()/cola.getDimensionTablero(), jB.getY()/cola.getDimensionTablero(), cola.getMatriz().busquedaValor(x, y), jB.getText());
              } });
             
            }                   
        }
        jButton1.setText(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getFichaMano());
        jugador.getListaJugadores().getPrimeraMano().getListaMano().setPrimeraFichaMano(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getSiguiente());
jButton2.setText(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getFichaMano());
        jugador.getListaJugadores().getPrimeraMano().getListaMano().setPrimeraFichaMano(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getSiguiente());
jButton3.setText(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getFichaMano());
        jugador.getListaJugadores().getPrimeraMano().getListaMano().setPrimeraFichaMano(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getSiguiente());
jButton4.setText(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getFichaMano());
        jugador.getListaJugadores().getPrimeraMano().getListaMano().setPrimeraFichaMano(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getSiguiente());
jButton5.setText(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getFichaMano());
        jugador.getListaJugadores().getPrimeraMano().getListaMano().setPrimeraFichaMano(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getSiguiente());
jButton6.setText(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getFichaMano());
        jugador.getListaJugadores().getPrimeraMano().getListaMano().setPrimeraFichaMano(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getSiguiente());
jButton7.setText(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano().getFichaMano());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Lista Jugadores");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Cola de Fichas");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Lista de Fichas ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Lista de Palabras");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Matriz");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("2");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("1");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("3");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("4");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("5");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("VALIDAR TIRO");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("CANCELAR TIRO");

        jButton20.setText("jButton20");

        jScrollPane1.setViewportView(jTextPane1);

        jButton21.setText("Agregar Palabra");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(359, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton17)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton16))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton14)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton13))
                                            .addComponent(jTextField1))
                                        .addGap(11, 11, 11))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton13)
                                    .addComponent(jButton14)))
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15)
                            .addComponent(jButton16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton17)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton18)
                                .addComponent(jButton19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   
        try
        {
            
            FileWriter fichero = null;
            PrintWriter pw = null;
            try
            {
                
                fichero = new FileWriter("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaJugadores.txt");
                pw = new PrintWriter(fichero);
                pw.println("digraph G");
                pw.println("{");
                jugador.getListaJugadores().setJugadorAuxiliar(jugador.getListaJugadores().getUltimoJugador());
                do {
                    pw.println(jugador.getListaJugadores().getJugadorAuxiliar().getJugador()+";");
                    jugador.getListaJugadores().setJugadorAuxiliar(jugador.getListaJugadores().getJugadorAuxiliar().getSiguiente());
                } while (jugador.getListaJugadores().getJugadorAuxiliar()!= jugador.getListaJugadores().getUltimoJugador());
                jugador.getListaJugadores().setJugadorAuxiliar(jugador.getListaJugadores().getUltimoJugador());
                do {
                    pw.println(jugador.getListaJugadores().getJugadorAuxiliar().getJugador()+" -> "+jugador.getListaJugadores().getJugadorAuxiliar().getSiguiente().getJugador()+";");
                    jugador.getListaJugadores().setJugadorAuxiliar(jugador.getListaJugadores().getJugadorAuxiliar().getSiguiente());
                } while (jugador.getListaJugadores().getJugadorAuxiliar()!= jugador.getListaJugadores().getUltimoJugador());
                pw.println("}");
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    // Nuevamente aprovechamos el finally para
                    // asegurarnos que se cierra el fichero.
                    if (null != fichero)
                        fichero.close();
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
            }
            
            String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";
            String fileInputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaJugadores.txt";
            String fileOutputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaJugadores.jpg";
            String tParam = "-Tjpg";
            String tOParam = "-o";
            String[] cmd = new String[5];
            cmd[0] = dotPath;
            cmd[1] = tParam;
            cmd[2] = fileInputPath;
            cmd[3] = tOParam;
            cmd[4] = fileOutputPath;
            Runtime rt = Runtime.getRuntime();
            rt.exec( cmd );
            
            
        } catch (IOException ex) {
            Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            contadorCola = 1;
            try
            {
                FileWriter fichero = null;
                PrintWriter pw = null;
                try
                {
                    
                    fichero = new FileWriter("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\colaFichas.txt");
                    pw = new PrintWriter(fichero);
                    pw.println("digraph G");
                    pw.println("{");
                    cola.getColaF().setColaAuxiliar(cola.getColaF().getPrimeraFicha());
                    do {
                        pw.println("A"+contadorCola+"[label = \""+cola.getColaF().getColaAuxiliar().getficha()+"\"];");
                        cola.getColaF().setColaAuxiliar(cola.getColaF().getColaAuxiliar().getSiguiente());
                        contadorCola = contadorCola+1;
                    } while (cola.getColaF().getColaAuxiliar()!= null);
                    do {
                        pw.println("A"+contadorCola+" -> "+"A"+(contadorCola+1)+";");
                        contadorCola = contadorCola-1;
                    } while (contadorCola > 0);
                    pw.println("}");
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        // Nuevamente aprovechamos el finally para
                        // asegurarnos que se cierra el fichero.
                        if (null != fichero)
                            fichero.close();
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";
                String fileInputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\colaFichas.txt";
                String fileOutputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\colaFichas.jpg";
                String tParam = "-Tjpg";
                String tOParam = "-o";
                String[] cmd = new String[5];
                cmd[0] = dotPath;
                cmd[1] = tParam;
                cmd[2] = fileInputPath;
                cmd[3] = tOParam;
                cmd[4] = fileOutputPath;
                Runtime rt = Runtime.getRuntime();
                rt.exec( cmd );
                
            } catch (IOException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        contadorMano = 1;
        FileWriter fichero = null;
            PrintWriter pw = null;
            try
            {
                
                fichero = new FileWriter("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaManoJugador"+contadorLISTA+".txt");
                pw = new PrintWriter(fichero);
                pw.println("digraph G");
                pw.println("{");
                jugador.getListaJugadores().getPrimeraMano().getListaMano().setManoAuxiliar(jugador.getListaJugadores().getPrimeraMano().getListaMano().getPrimeraFichaMano());
                do {
                    pw.println("A"+contadorMano+"[label = \""+jugador.getListaJugadores().getPrimeraMano().getListaMano().getManoAuxiliar().getFichaMano()+"\"];");
                    contadorMano = contadorMano+1;
                    jugador.getListaJugadores().getPrimeraMano().getListaMano().setManoAuxiliar(jugador.getListaJugadores().getPrimeraMano().getListaMano().getManoAuxiliar().getSiguiente());
                } while (jugador.getListaJugadores().getPrimeraMano().getListaMano().getManoAuxiliar().getSiguiente()!=null);
                 pw.println("A"+contadorMano+"[label = \""+jugador.getListaJugadores().getPrimeraMano().getListaMano().getManoAuxiliar().getFichaMano()+"\"];");
                do {
                    pw.println("A"+contadorMano+" -> "+"A"+(contadorMano+1)+";");
                    contadorMano= contadorMano-1;
                } while (contadorMano>0);
                pw.println("}");
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    try {
                        // Nuevamente aprovechamos el finally para
                        // asegurarnos que se cierra el fichero.
                        if (null != fichero)
                            fichero.close();
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                    String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";
                    String fileInputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaManoJugador"+contadorLISTA+".txt";
                    String fileOutputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaManoJugador"+contadorLISTA+".jpg";
                    String tParam = "-Tjpg";
                    String tOParam = "-o";
                    String[] cmd = new String[5];
                    cmd[0] = dotPath;
                    cmd[1] = tParam;
                    cmd[2] = fileInputPath;
                    cmd[3] = tOParam;
                    cmd[4] = fileOutputPath;
                    Runtime rt = Runtime.getRuntime();
                    rt.exec( cmd );
                } catch (IOException ex) {
                    Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
            try
            {
                FileWriter fichero = null;
                PrintWriter pw = null;
                try
                {
                    
                    fichero = new FileWriter("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaPalabrlas.txt");
                    pw = new PrintWriter(fichero);
                    pw.println("digraph G");
                    pw.println("{");
                    cola.getListaSimpleD().setAuxiliarDiccionario(cola.getListaSimpleD().getPrimeraPalabra());
                    do {
                        pw.println(cola.getListaSimpleD().getAuxiliarDiccionario().getPalabra()+";");
                        cola.getListaSimpleD().setAuxiliarDiccionario(cola.getListaSimpleD().getAuxiliarDiccionario().getSiguiente());
                    } while (cola.getListaSimpleD().getAuxiliarDiccionario().getSiguiente()!=null);
                    cola.getListaSimpleD().setAuxiliarDiccionario(cola.getListaSimpleD().getPrimeraPalabra());
                    do {
                        pw.println(cola.getListaSimpleD().getAuxiliarDiccionario().getPalabra()+" -> "+cola.getListaSimpleD().getAuxiliarDiccionario().getSiguiente().getPalabra()+";");
                        cola.getListaSimpleD().setAuxiliarDiccionario(cola.getListaSimpleD().getAuxiliarDiccionario().getSiguiente());
                    } while (cola.getListaSimpleD().getAuxiliarDiccionario().getSiguiente()!=null);
                    pw.println("}");
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        // Nuevamente aprovechamos el finally para
                        // asegurarnos que se cierra el fichero.
                        if (null != fichero)
                            fichero.close();
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";
                String fileInputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaPalabrlas.txt";
                String fileOutputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaPalabrlas.jpg";
                String tParam = "-Tjpg";
                String tOParam = "-o";
                String[] cmd = new String[5];
                cmd[0] = dotPath;
                cmd[1] = tParam;
                cmd[2] = fileInputPath;
                cmd[3] = tOParam;
                cmd[4] = fileOutputPath;
                Runtime rt = Runtime.getRuntime();
                rt.exec( cmd );
            } catch (IOException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                try
                {
                    FileWriter fichero = null;
                    PrintWriter pw = null;
                    try
                    {
                        x = 0;
                        y = 0;
                        fichero = new FileWriter("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\matriz"+contadorM+".txt");
                        pw = new PrintWriter(fichero);
                        pw.println("digraph G");
                        pw.println("{");
                        for (int i = 0; i < cola.getDimensionTablero(); i++) {
                            for (int j = 0; j < cola.getDimensionTablero(); j++) {
                                pw.println("A"+contadorMatriz+"[label = \""+cola.getMatriz().busquedaValor(i, j)+" "+cola.getMatriz().busquedaPalabra(i, j)+"X="+i+" Y="+j+"\"];");
                                contadorMatriz = contadorMatriz +1;
                            }
                        }
                        contadorMatriz = 0;
                        contadoMX = contadoMY = cola.getDimensionTablero()*cola.getDimensionTablero();
                        do {
                            for (int i = 0; i < (cola.getDimensionTablero()-1); i++) {
                                pw.println("A"+contadoX+" -> "+"A"+(contadoX+1)+";");
                                contadoX = contadoX+1;
                                auxCon = auxCon+1;
                            }
                            contadoX = contadoX+1;
                            for (int i = 0; i < (cola.getDimensionTablero()-1); i++) {
                                pw.println("A"+contadoY+" -> "+"A"+(contadoY+cola.getDimensionTablero())+";");
                                contadoY = contadoY+1;
                                auxCon = auxCon+1;
                            }
                            contadoY = contadoY+1;
                            for (int i = 0; i < (cola.getDimensionTablero()-1); i++) {
                                pw.println("A"+contadoMX+" -> "+"A"+(contadoMX-1)+";");
                                contadoMX = contadoMX-1;
                                auxCon = auxCon+1;
                            }
                            contadoX = contadoX-1;
                            for (int i = 0; i < (cola.getDimensionTablero()-1); i++) {
                                pw.println("A"+contadoMY+" -> "+"A"+(contadoMY+cola.getDimensionTablero())+";");
                                contadoMY = contadoMY-1;
                                auxCon = auxCon+1;
                            }
                            contadoMY = contadoMY-1;
                        } while (auxCon<((cola.getDimensionTablero()-1)*(cola.getDimensionTablero()))*4);
                        pw.println("}");
                    } catch (Exception e) {
                        e.printStackTrace();
                    } finally {
                        try {
                            // Nuevamente aprovechamos el finally para
                            // asegurarnos que se cierra el fichero.
                            if (null != fichero)
                                fichero.close();
                        } catch (Exception e2) {
                            e2.printStackTrace();
                        }
                    }
                    String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";
                    String fileInputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\matriz"+contadorM+".txt";
                    String fileOutputPath = "C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\matriz"+contadorM+".jpg";
                    String tParam = "-Tjpg";
                    String tOParam = "-o";
                    String[] cmd = new String[5];
                    cmd[0] = dotPath;
                    cmd[1] = tParam;
                    cmd[2] = fileInputPath;
                    cmd[3] = tOParam;
                    cmd[4] = fileOutputPath;
                    Runtime rt = Runtime.getRuntime();
                    rt.exec( cmd );
                } catch (IOException ex) {
                    Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       ImageIcon icon = new ImageIcon("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaJugadores.jpg");
       jTextPane1.setText("");       
       jTextPane1.insertIcon(icon);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
            ImageIcon icon = new ImageIcon("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\colaFichas.jpg");
            jTextPane1.setText("");
            jTextPane1.insertIcon(icon);
            
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
            ImageIcon icon = new ImageIcon("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaManoJugador"+contadorLISTA+".jpg");
            jTextPane1.setText("");
            jTextPane1.insertIcon(icon);
            contadorLISTA = contadorLISTA +1;
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       ImageIcon icon = new ImageIcon("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\listaPalabrlas.jpg");
       jTextPane1.setText("");       
       jTextPane1.insertIcon(icon);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       ImageIcon icon = new ImageIcon("C:\\Users\\Valdez\\Desktop\\Nueva carpeta (2)\\matriz"+contadorM+".jpg");
       jTextPane1.setText("");       
       jTextPane1.insertIcon(icon);
       contadorM = contadorM+1;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        jugador.getListaJugadores().siguiente();
        jLabel1.setText(jugador.getListaJugadores().getUltimoJugador().getJugador());
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        cola.getMatriz().setAuxLateral(cola.getMatriz().getLateral());
        cola.getMatriz().setAuxCabecera(cola.getMatriz().getCabecera());
        for (int i = 0; i < cola.getDimensionTablero(); i++) {
            for (int j = 0; j < cola.getDimensionTablero(); j++) {
                if (cola.getMatriz().busquedaPalabra(i, j).equals("")) {
                    
                }else{
                    do {                        
                         
                    } while (cola.getMatriz().getLateral().busqueda(j).getFila().getPrimero().getDerecha().getLetra()!= "" && cola.getMatriz().getLateral().busqueda(j).getFila().getPrimero().getDerecha().getValorCasilla()!= 0);
                    
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       palabraDiccionario palabraD = new palabraDiccionario(jTextField1.getText());
       cola.getListaSimpleD().agregarPalabra(palabraD);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        valorAuxiliar = jButton1.getText();
        jButton1.hide();
        jugador.getListaJugadores().getPrimeraMano().getListaMano().agregarFichaMano(jugador.getmJ());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               valorAuxiliar = jButton2.getText();
               jButton2.hide();
                jugador.getListaJugadores().getPrimeraMano().getListaMano().agregarFichaMano(jugador.getmJ());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       valorAuxiliar = jButton3.getText();
       jButton3.hide();
       jugador.getListaJugadores().getPrimeraMano().getListaMano().agregarFichaMano(jugador.getmJ());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               valorAuxiliar = jButton4.getText();
               jButton4.hide();
               jugador.getListaJugadores().getPrimeraMano().getListaMano().agregarFichaMano(jugador.getmJ());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                valorAuxiliar = jButton5.getText();
                jButton5.hide();
                jugador.getListaJugadores().getPrimeraMano().getListaMano().agregarFichaMano(jugador.getmJ());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                valorAuxiliar = jButton6.getText();
                jButton6.hide();
                jugador.getListaJugadores().getPrimeraMano().getListaMano().agregarFichaMano(jugador.getmJ());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                valorAuxiliar = jButton7.getText();
                jButton7.hide();
                jugador.getListaJugadores().getPrimeraMano().getListaMano().agregarFichaMano(jugador.getmJ());
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
